src/actions/guides/command_line_tasks/built_in.cr, src/actions/guides/command_line_tasks/custom_tasks.cr, src/components/guides/sidebar.cr
=> Add Command Line Tasks guide

src/actions/blog/show.cr, src/components/blog/published_at.cr, src/css/app.scss, src/css/components/_markdown-content.scss, src/pages/blog/index_page.cr, src/pages/blog/show_page.cr, src/pages/blog_layout.cr, src/pages/guide_layout.cr, src/posts/base_post.cr, src/posts/introducing_the_lucky_blog.cr, src/queries/post_query.cr
=> Show blog posts

spec/html_autolink_spec.cr, src/utils/custom_markdown_renderer.cr, src/utils/html_autolink.cr
=> Autolink markdown

src/actions/guides/redirect.cr, src/actions/why_lucky/redirect.cr, src/guides/overview.md
=> Redirect old paths

src/components/blog/published_at.cr, src/pages/blog/index_page.cr, src/pages/blog/show_page.cr, src/posts/base_post.cr, src/posts/introducing_the_lucky_blog.cr, src/queries/post_query.cr
=> Publish dates & sort them

src/actions/guides/frontend/asset-handling.cr, src/actions/guides/frontend/rendering_html.cr, src/js/app.js
* Updated link to laravel docs
* Added ton more docs and examples to creating custom tags, and how to use attributes.
=> Updating frontend guides

src/actions/guides/http_and_routing/link_generation.cr, src/actions/guides/http_and_routing/request_and_response.cr, src/actions/guides/http_and_routing/routing_and_params.cr, src/actions/guides/http_and_routing/sessions_and_cookies.cr
* Updates some text for clarity
* Adds references to a ton more available methods
* Additional links and examples
=> Updating http and routing docs

src/actions/guides/command_line_tasks/built_in.cr, src/actions/guides/command_line_tasks/custom_tasks.cr
* Fixes some syntax highlighting
* Adds a lot more docs about how to build and run custom tasks
=> Updating docs on custom tasks

src/actions/guides/http_and_routing/before_after_actions.cr, src/actions/guides/http_and_routing/http_handlers.cr, src/components/guides/sidebar.cr
* Adds docs about before and after pipes
* Adds docs on using handlers and customizing them
=> Adding more routing docs

src/actions/guide_action.cr, src/actions/guides/database/validating-saving-deleting.cr, src/actions/guides/deploying/heroku.cr, src/actions/guides/frontend/rendering_html.cr, src/actions/guides/getting-started/concepts.cr, src/actions/guides/getting-started/installing.cr, src/actions/guides/getting-started/why_lucky.cr, src/actions/guides/http_and_routing/request_and_response.cr, src/actions/guides/http_and_routing/routing_and_params.cr, src/actions/guides/json_and_apis/cors.cr, src/actions/guides/json_and_apis/saving-to-the-database.cr
fixes #6 
There's a lot of pages to do, but just want to make sure this is the path you were thinking. If this looks good, I'll finish the rest.
=> Converting static paths to helper paths

src/actions/guides/database/raw-sql.cr, src/actions/guides/database/validating-saving-deleting.cr, src/actions/guides/getting-started/why_lucky.cr, src/actions/guides/http_and_routing/before_after_actions.cr, src/actions/guides/http_and_routing/request_and_response.cr, src/actions/guides/http_and_routing/routing_and_params.cr, src/actions/guides/json_and_apis/parsing-json-requests.cr
* Fixes a few anchors with the new constant format
* Fixes crystal paths to resolve to latest version
* DB query had an example using backticks instead of quotes.
* Removed random placed anchor that doesn't seem to be called from anywhere internally.
=> More fixes

src/actions/guides/frontend/rendering_html.cr, src/actions/guides/getting-started/concepts.cr, src/actions/guides/http_and_routing/before_after_actions.cr, src/actions/guides/http_and_routing/http_handlers.cr, src/actions/guides/http_and_routing/request_and_response.cr, src/actions/guides/http_and_routing/routing_and_params.cr, src/actions/guides/http_and_routing/security_headers.cr, src/components/guides/sidebar.cr
I broke these out in to separate commits, but these are all updates on what's available in lucky master. 
* fallback routing
* special tags like `nbsp`
* Secure headers
* structure change
=> Guides updates 3

src/components/shared/layout_head.cr, src/css/components/_markdown-content.scss, src/pages/main_layout.cr
Closes #8 
https://lucky-website-pr-39.herokuapp.com
=> All new home page

src/actions/guides/frontend/rendering_html.cr
This adds in docs for some of the pages helpers.
=> document page helpers

src/actions/guides/getting-started/installing.cr, src/models/lucky_cli_version.cr
=> Update docs for Lucky CLI version 0.15.0

src/actions/guides/http_and_routing/before_after_actions.cr
=> Document skipping pipes

src/actions/guides/getting-started/installing.cr
=> fixing mention of wrong crystal version

src/pages/guide_layout.cr
Algolia docsearch is looking for a particular HTML/CSS structure.
This updates the HTML to match https://github.com/algolia/docsearch-configs/blob/master/configs/luckyframework.json
=> Fix Algolia docsearch

src/actions/guides/frontend/asset-handling.cr
=> Adding docs on setting the asset host. 

src/actions/guides/database/validating-saving-deleting.cr
=> Adds in docs for Form#param_key.

src/actions/guides/json_and_apis/cors.cr
Fixes #46
CORS is confusing... I don't think these docs really make it "clear", but they do provide a full example that could technically be dropped right in to an app.
=> Adding in full CORS example. 

src/actions/guides/database/intro_to_avram_and_orms.cr, src/components/guides/sidebar.cr
This adds in the new "Intro to Avram" page for database.
I'll be submitting each new portion for the database as a separate PR just to make them easier to digest, and merge in little by little.
=> adding in the first page for the new databse section
